In [2]:
# Numpy array
## Similar to lists, except that every element of an array must be of the same type
## Example
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a[1])          
b = np.array([1, 2, 3, 4, 5], float)
print(b[1])          

2
2.0


In [4]:
# Given a space separated list of numbers, print a reversed NumPy array with the element type float
def arrays(arr):
    return np.array(list(reversed(arr)), float)

arr = input().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [7]:
# Shape 
## The shape tool gives a tuple of array dimensions.
## It can be used to change the dimensions of an array.
### Get the array dimensions
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([[1, 2], [3, 4], [5, 6]])
print(array_1.shape)     
print(array_2.shape)
### Change the array dimensions
change_array = np.array([1, 2, 3, 4, 5, 6])
change_array.shape = (3, 2)
print(change_array)      

# Reshape
## The reshape tool gives a new shape to an array without changing its data. 
## It creates a new array and does not modify the original array itself.
array_3 = np.array([1, 2, 3, 4, 5, 6])
print(np.reshape(array_3, (3, 2)))

(5,)
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [8]:
# Given a space separated list of nine integers, convert the list into a 3*3 NumPy array
def array_reshape(arr):
    return np.reshape(arr, (3, 3))

arr = np.array(input().split(), int)
result = array_reshape(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Zeros & Ones
print(np.zeros((1, 2), dtype = np.int))
print(np.ones((1, 2), dtype = np.int))

[[0 0]]
[[1 1]]


In [13]:
# Given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions
# Print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones
# Example: 3 (Row) 3 (Column) 3 (Number)
## [[[0 0 0]
##   [0 0 0]
##   [0 0 0]]

## [[0 0 0]
##  [0 0 0]
##  [0 0 0]]

## [[0 0 0]
##  [0 0 0]
##  [0 0 0]]]

## [[[1 1 1]
##   [1 1 1]
##   [1 1 1]]

## [[1 1 1]
##  [1 1 1]
##  [1 1 1]]

## [[1 1 1]
##  [1 1 1]
##  [1 1 1]]]
dim = tuple(map(int, input().split()))
print(np.zeros(dim, dtype = np.int))
print(np.ones(dim, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [17]:
# Concatenate
## Two or more arrays can be concatenated together using the concatenate function with a tuple of arrays to be joined
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.array([7, 8, 9])
print(np.concatenate((array_1, array_2, array_3)))
## For more than one dimension array, specify the axis along which multiple arrays are concatenated 
### axis = 1: By column, next to each other
### axis = 0: By row, on top of each other 
array_1 = np.array([[1, 2, 3], [0, 0, 0]])
array_2 = np.array([[0, 0, 0], [7, 8, 9]])
print(np.concatenate((array_1, array_2), axis = 1))
print(np.concatenate((array_1, array_2), axis = 0))   


[1 2 3 4 5 6 7 8 9]
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


In [19]:
# Given two integer arrays of size N*P and M*P, concatenate the arrays along axis 0
## The first line contains space separated integers, N, M, and P.
## The next N lines contain the space separated elements of the P columns.
## The next M lines contain the space separated elements of the P columns.
n, m, p = map(int, input().split())
array_1 = np.array([input().split() for i in range(n)], dtype = np.int)
array_2 = np.array([input().split() for i in range(m)], dtype = np.int)
print(np.concatenate((array_1, array_2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [25]:
# Transpose & Flatten
## Transpose
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.transpose())
## Flatten
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.flatten())

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


In [26]:
# Given a N*M integer array matrix with space separated elements, print the transpose and flatten results
n, m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], dtype = np.int)
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
# Min & Max
## Min / Max: Returns the minimum / maximum value along a given axis 
## 0: Across all rows; 1: Across all columns; Default: All elements
my_array = np.array([[2, 5], [3, 7], [1, 3], [4, 0]])
print(np.min(my_array, axis = 0))       
print(np.min(my_array, axis = 1))       
print(np.min(my_array))

[1 0]
[2 3 1 0]
0


In [9]:
# Given a 2-D array with dimensions N*M, perform the min function over axis 1 and then find the max value
n, m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], dtype = np.int)
print(np.max(np.min(arr, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


In [10]:
# Sum & Product
## Sum / Product: Returns the sum / product of array elements over a given axis
## 0: Across all rows; 1: Across all columns; Default: All elements
my_array = np.array([ [1, 2], [3, 4] ])
print(np.prod(my_array, axis = 0))           
print(np.prod(my_array, axis = 1))       
print(np.prod(my_array))

[3 8]
[ 2 12]
24


In [11]:
# Given a 2-D array with dimensions N*M, perform the sum over axis 0 and find its product
n, m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], dtype = np.int)
print(np.prod(np.sum(arr, axis = 0)))

2 2
1 2
3 4
24


In [13]:
# Mean & Variance
## Computes the arithmetic mean along the specified axis
## Computes the arithmetic variance along the specified axis
## Computes the arithmetic standard deviation along the specified axis

# Given a 2-D array with dimensions N*M, find the following values
## The mean along axis 1
## The var along axis 0
## The std along axis None
n, m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], dtype = np.int)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(np.std(arr))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [4]:
# Identity
## Returns a square matrix with all the main diagonal elements as 1 and the rest as 0
## The default data type is float.
print(np.identity(3))

# Eye 
## Returns a 2-D array with 1s on the diagonal and 0s elsewhere
## N: The number of rows
## M: The number of columns
## k: Index of the diagonal: 0 refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
print(np.eye(3, k = 1))

# Print an array of size N*M with its main diagonal elements as 1s and 0s everywhere else
n, m = map(int, input().split())
print(np.eye(n, m, k = 0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Dot product: np.dot(a, b)
# Cross product: np.cross(a, b)

# Given two arrays (Both have dimensions of N*N), compute their matrix product
n = int(input())
a = np.array([input().split() for i in range(n)], dtype = int)
b = np.array([input().split() for i in range(n)], dtype = int)
print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [9]:
# Inner product (Generalization of the dot product): np.inner()
## In a vector space, it is a way to multiply vectors together.
## The result of the multiplication is a scalar.

# Outer product: np.outer()
## Given two vectors, u = (u1, u2, ..., um) and v = (v1, v2, ..., vn), 
## The outer product is defined by multiplying each element of u by each element of v (m*n matrix)

# Given two arrays A and B, compute their inner and outer product
a = np.array(input().split(), dtype = int)
b = np.array(input().split(), dtype = int)
print(np.inner(a, b))
print(np.outer(a, b))


0 1
2 3
3
[[0 0]
 [2 3]]


In [11]:
# Floor: The floor of x is the largest integer i where i <= x.
# Ceil: The ceiling of x is the smallest integer i where i >= x.
# Rint: Rounds to the nearest integer of input element-wise

# Given a 1-D array, print the floor, ceil and rint of all the elements of array
a = np.array(input().split(), dtype = float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]
